### ISSUE TITLE
Please Add 'Sum' in reduction.py or get data from tui

### ISSUE THREAD

**Issue by RebelYoung** [ansys/pyfluent#1960] opened 2023-09-07 03:02 UTC
### 📝 Description of the feature

I wanna a 'Sum' function in `reduction.py`.
![image](https://github.com/ansys/pyfluent/assets/59256512/fddb52dc-07df-4e4d-90cf-32d4b7ec045e)
![image](https://github.com/ansys/pyfluent/assets/59256512/080ade61-8abb-4f20-b8fd-4d6dc83f8b18)

I found the `named expressions' can not transform with 'custom field functions.
So, another option is return the result from `tui.report.surface_integrals.sum`.
```
report> surf
Available options: ("area" "area-weighted-avg" "vector-based-flux" "vector-flux" "vector-weighted-average" "facet-avg" "facet-min" "facet-max" "flow-rate" "integral" "mass-flow-rate" "mass-weighted-avg" "standard-deviation" "sum" "uniformity-index-area-weighted" "uniformity-index-mass-weighted" "vertex-avg" "vertex-min" "vertex-max" "volume-flow-rate")
```

Thank you.

**Comment by RebelYoung** [comment] 2023-09-11 01:37
I just found a different `reduction.py` in `miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\services`. There are more functions than `miniconda3\envs\py39\Lib\site-packages\ansys\fluent\core\solver\function\reduction.py`. However, there is no `Sum` function.
![image](https://github.com/ansys/pyfluent/assets/59256512/ed7836ba-c072-4ada-8dd9-d82ae8c70dd0)

**Comment by RebelYoung** [comment] 2023-09-11 01:40
I need the sum feature, because my named expression has XFaceArea and YFaceArea, just need sum not intergral function.

**Comment by RebelYoung** [comment] 2023-09-11 02:00
Refer to usage in `function/reduction.py', it always has an error in ` response = self.service.area_average(request)`.
```
    def area_average(self, expression, locations, ctxt=None) -> Any:
        """Get area average."""
        request = ReductionProtoModule.AreaAveRequest()
        request.expression = expression
        request.locations.extend(self._get_location_string(locations, ctxt))
        response = self.service.area_average(request)
        return response.value
```
![image](https://github.com/ansys/pyfluent/assets/59256512/18069dd6-f392-4758-af1c-e314b72f9c41)
![image](https://github.com/ansys/pyfluent/assets/59256512/8996a06e-da72-4662-98c4-211a64297221)


Please, add some examples for usage of these function.

**Comment by RebelYoung** [comment] 2023-09-11 02:22
@mkundu1 @prmukherj Please help me.

**Comment by prmukherj** [comment] 2023-09-11 06:32
@RebelYoung, there are examples in the documentation.
For example of area_average, one can either do: 

>>> solver.reduction.area_average(expression="AbsolutePressure", locations=s.setup.boundary_conditions.velocity_inlet)       

OR,

>>> from ansys.fluent.core.solver.function import reduction                                                             
>>> reduction.area_average(expr="AbsolutePressure", locations=s.setup.boundary_conditions.velocity_inlet)

**Comment by RebelYoung** [comment] 2023-09-11 06:48
> @RebelYoung, there are examples in the documentation. For example of area_average, one can either do:
> 
> > > > solver.reduction.area_average(expression="AbsolutePressure", locations=solver.setup.boundary_conditions.velocity_inlet)
> 
> OR,
> 
> > > > from ansys.fluent.core.solver.function import reduction
> > > > reduction.area_average(expr="AbsolutePressure", locations=solver.setup.boundary_conditions.velocity_inlet)
> 
> Prefer option 1 for any use cases.

@prmukherj yes, I have tried the template, option 1 you provide. But，it occured the error as my figure in my last reply.

**Comment by RebelYoung** [comment] 2023-09-11 06:52
![image](https://github.com/ansys/pyfluent/assets/59256512/57a43a9e-4fb9-4a15-a896-381d5b98a773)
![image](https://github.com/ansys/pyfluent/assets/59256512/b2d45bfe-3091-49f4-82a9-59c1d3102e70)
It happens in any functions, like `area`, `area_average`, `force`, etc.
@prmukherj

**Comment by prmukherj** [comment] 2023-09-11 10:24
@RebelYoung, Could you please provide the entire script to reproduce this issue?
Thank you

**Comment by RebelYoung** [comment] 2023-09-11 14:02
> @RebelYoung, Could you please provide the entire script to reproduce this issue? Thank you



> @RebelYoung, Could you please provide the entire script to reproduce this issue? Thank you
![image](https://github.com/ansys/pyfluent/assets/59256512/c5521f30-254b-4b8e-ba18-a48b150b968e)

@prmukherj hello, I tested a simple duct case,  and compare two `reduction` files.
You can see, the conventional reduction run completely, but the `service/reduction` failed. 
The `RuntimeError` happens in every functions in `service/reduction.py`.
![image](https://github.com/ansys/pyfluent/assets/59256512/b059d215-c2e8-4220-882f-fc49ea9934d4)
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[19], line 1
----> 1 solver.reduction.area(
      2     locations=solver.setup.boundary_conditions.pressure_inlet
      3 )

File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\services\reduction.py:275, in Reduction.area(self, locations, ctxt)
    273 request = ReductionProtoModule.AreaRequest()
    274 request.locations.extend(self._get_location_string(locations, ctxt))
--> 275 response = self.service.area(request)
    276 return response.value

File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\services\error_handler.py:15, in catch_grpc_error.<locals>.func(*args, **kwargs)
     13     return f(*args, **kwargs)
     14 except grpc.RpcError as ex:
---> 15     raise RuntimeError(ex.details()) from None

RuntimeError:
```
No infomation after the last word 'RuntimeError'.

**Comment by RebelYoung** [comment] 2023-09-11 14:13
@prmukherj Another error in conventional reduction is `RuntimeError` when compute for a vector variable, like `Velocity`, but it 
still outputs a result. It broke down the code.  
![image](https://github.com/ansys/pyfluent/assets/59256512/9c9bb0d1-c47e-49a3-abbf-0226c94c68e3)
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\function\reduction.py:178, in _extent_expression(f_string, extent_name, expr, locations, ctxt)
    177 try:
--> 178     numerator += val * extent
    179     denominator += extent

TypeError: unsupported operand type(s) for +=: 'float' and 'list'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[29], line 1
----> 1 reduction.area_average(
      2     expr='Velocity',
      3     locations=solver.setup.boundary_conditions.pressure_inlet
      4 )

File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\function\reduction.py:259, in area_average(expr, locations, ctxt)
    246 def area_average(expr, locations, ctxt=None):
    247     """Compute the area averaged value of the specified expression over the
    248     specified locations.
    249 
   (...)
    257     float
    258     """
--> 259     return _extent_average("Area", expr, locations, ctxt)

File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\function\reduction.py:201, in _extent_average(extent_name, expr, locations, ctxt)
    200 def _extent_average(extent_name, expr, locations, ctxt):
--> 201     return _extent_expression(f"{extent_name}Ave", extent_name, expr, locations, ctxt)

File ~\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\function\reduction.py:181, in _extent_expression(f_string, extent_name, expr, locations, ctxt)
    179         denominator += extent
    180     except TypeError:
--> 181         raise RuntimeError(val)
    182 if denominator == 0.0:
    183     raise BadReductionRequest("Zero extent computed for average")

RuntimeError: [280.9091002985646, -8.850462237150465e-05, 0.0]
```

**Comment by mkundu1** [comment] 2023-09-11 15:28
Hi @RebelYoung, what is the Ansys version you're using?

**Comment by RebelYoung** [comment] 2023-09-12 02:22
> Hi @RebelYoung, what is the Ansys version you're using?

@mkundu1 ansys fluent 2023R1 and pyfluent 0.17.0

**Comment by seanpearsonuk** [comment] 2023-09-20 16:14
@prmukherj this looks like it will be fixed by the vector changes that are going into Fluent 24R1. Please confirm. Closing on assumption.

**Closed by seanpearsonuk** 2023-09-20 16:14 UTC
Labels: enhancement

**Comment by prmukherj** [comment] 2023-09-20 20:42
@seanpearsonuk, right.
