### ISSUE TITLE
Issue with TaskObject. Arguments attribute leading to session shutdown

### ISSUE THREAD

**Issue by PyPablo** [ansys/pyfluent#1249] opened 2023-01-09 15:02 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

, I am receiving a Cortex Error in Fluent session and subsequent fluent shutdown when calling the following command
mysession.workflow.TaskObject['Import Geometry'].Arguments

with the watertight workflow, pyfluent version 0.12.dev13 and fluent 23.1 November 7th release.

This did not happen with previous PyFluent build. Any idea why this is happening?

![Capture](https://user-images.githubusercontent.com/99959795/211339020-d9c14230-f4d0-4543-a78b-d0a1963a09fb.JPG)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by seanpearsonuk** [comment] 2023-01-09 16:36
First of all, I tried this out locally with my main branch, and reproduced it for 22.2 but not 23.1, where it was fine. So then I decided to pip install a succession of dev versions and try each out. This is the test script:
```
import ansys.fluent.core as pf
pf.set_ansys_version(22.2)
m=pf.launch_fluent(mode="meshing")
m.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
dir(m.workflow.TaskObject["Import Geometry"].Arguments)
pf.set_ansys_version(23.1)
m2=pf.launch_fluent(mode="meshing")
m2.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
dir(m2.workflow.TaskObject["Import Geometry"].Arguments)
```
I tried each of 0.12.dev[6, 8, 9, 12, 13] with 22.2 and 23.1 and could not reproduce this issue. @mkundu1 @ajain-work @prmukherj @hpohekar: are you able to reproduce this issue? We need to understand and resolve any issue for the full release. 

My guess is that my main branch behaviour will fix itself with codegen being run.

**Comment by PyPablo** [comment] 2023-01-09 16:54
This is what I get
![image](https://user-images.githubusercontent.com/99959795/211361324-7abf369b-7ff0-447f-ad0d-4ff0a5cfd6b2.png)
cc: @seanpearsonuk

**Comment by mkundu1** [comment] 2023-01-09 17:14
I'm not able to reproduce with 22.2 or 23.1 Fluent. I have generated code for both versions of Fluent.

**Comment by hpohekar** [comment] 2023-01-10 05:57
> import ansys.fluent.core as pf
> pf.set_ansys_version(22.2)
> m=pf.launch_fluent(mode="meshing")
> m.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
> dir(m.workflow.TaskObject["Import Geometry"].Arguments)
> pf.set_ansys_version(23.1)
> m2=pf.launch_fluent(mode="meshing")
> m2.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
> dir(m2.workflow.TaskObject["Import Geometry"].Arguments)

@seanpearsonuk I tried with both 22.2 and 23.1, it's not reproducible.

![image](https://user-images.githubusercontent.com/106588300/211472692-8f2f3ef1-eff8-4414-8da1-0ae1de570392.png)

**Comment by PyPablo** [comment] 2023-01-10 10:01
I have downloaded and reinstalled latest Fluent 23.1 release, then created a new virtual environment and downloaded dev version with 

git clone https://github.com/pyansys/pyfluent.git
cd pyfluent
%pyEnv%\pip install pip -U
%pyEnv%\pip install -e .

The problem persists (in 23.1)

cc @seanpearsonuk, @mkundu1

**Comment by PyPablo** [comment] 2023-01-10 12:21
Ok, I completely deleted all my Ansys 23.1 related products, all temp and appdata, reinstalled everything again (new 23.1 release, new virtual environment and new pyfluent install) and it works. I think the issue here is in Fluent 23.1 installation. As @seanpearsonuk , it does not work in 22.2 though

**Comment by seanpearsonuk** [comment] 2023-01-10 12:26
@PyPablo thanks. I only reproduced it temporarily 22R2 and pyfluent main branch, until I ran codegen.

**Comment by dnwillia-work** [comment] 2023-04-11 00:02
Is this fixed?  Looks like no PR was merged for it.  @PyPablo

**Comment by seanpearsonuk** [comment] 2023-05-18 12:49
Closing as this is not generally reproducible.

**Closed by seanpearsonuk** 2023-05-18 12:49 UTC
Labels: bug
