### ISSUE TITLE
Extracting unitless output parameters values throws errors

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#3413] opened 2024-10-22 09:17 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

We have a failing ARM test in our board which shows extraction of output parameters with no units doesnot work anymore.

[ERROR]        : <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "An error occurred in the server while evaluating the Scheme expression"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-22T09:03:37.1803196+00:00", grpc_status:2, grpc_message:"An error occurred in the server while evaluating the Scheme expression"}"
> 
 Traceback (most recent call last):
    fluent_output_table = self.fluent_session.settings.parameters.output_parameters.list()
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1739, in __call__
    return self.execute_command(**kwds)
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1663, in execute_command
    ret = self._execute_command(*args, **kwds)
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1733, in _execute_command
    ret = _fix_parameter_list_return(ret)
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1693, in _fix_parameter_list_return
    unit_labels = _fix_parameter_list_return.scheme_eval(
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\services\scheme_eval.py", line 343, in scheme_eval
    return self.eval(val)
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\services\scheme_eval.py", line 273, in eval
    response = self.service.scheme_eval(request)
  File "C:\Program Files\ANSYS Inc\v251\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\services\scheme_eval.py", line 76, in scheme_eval
    return self.__stub.SchemeEval(request, metadata=self.__metadata)
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py", line 1178, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "C:\Users\tprabhu\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "An error occurred in the server while evaluating the Scheme expression"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-22T09:03:37.1803196+00:00", grpc_status:2, grpc_message:"An error occurred in the server while evaluating the Scheme expression"}"
>

I am attaching transcript and case file for reference:
[StaticMixer__unitless.cas.zip](https://github.com/user-attachments/files/17473380/StaticMixer__unitless.cas.zip)

@seanpearsonuk @mkundu1 

### 📝 Steps to reproduce

import ansys.fluent.core as pyfluent
fluent_session = pyfluent.launch_fluent()
fluent_session.settings.file.read(file_type="case", file_name=filepath)
fluent_session.settings.parameters.input_parameters.expression[name] = {"value" : value}
fluent_output_table = fluent_session.settings.parameters.output_parameters.list()

initialization_type = fluent_session.settings.solution.initialization.initialization_type()
if initialization_type == "hybrid":
    fluent_session.settings.solution.initialization.hybrid_initialize()
elif initalization_type == "standard":
    fluent_session.settings.solution.initialization.standard_initialize()
fluent_session.settings.solution.run_calculation.iterate()

output_parameters_dict = OrderedDict()
fluent_output_table = fluent_session.settings.parameters.output_parameters.list()
for key, entry in fluent_output_table.items():
    output_parameters_dict[key] = OrderedDict()
    output_parameters_dict[key]['numeric_value'] = entry[0]
    output_parameters_dict[key]['units'] = entry[1]

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2025R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by seanpearsonuk** [comment] 2024-10-22 10:07
@tejalprabhu01 It looks like the API behaviour might have changed and the user code would need to adapt to be flexible. @cj-hodgson Did our testing need to adapt for such a change? Or are we not covering this, or testing in a more flexible way? Thanks.

**Comment by seanpearsonuk** [comment] 2024-10-22 10:07
@mkundu1

**Comment by cj-hodgson** [comment] 2024-10-22 10:41
@seanpearsonuk `fluent_output_table = solver_session.settings.parameters.output_parameters.list()` is tested in test_optislang_integration.py::test_simple_solve

**Comment by seanpearsonuk** [comment] 2024-10-22 10:56
Thanks @cj-hodgson. In general, `len(entry)` would need to be checked to cover the kind of case encountered by @tejalprabhu01. I would recommend doing that in the optiSLang code.

**Comment by tejalprabhu01** [comment] 2024-10-22 14:18
@seanpearsonuk I can add that check. But the error is thrown before that, already in line _fluent_input_table = fluent_session.settings.parameters.input_parameters.list()_
Also, this command works for parameters with units and therefore it must be working in test_optislang_integration.py::test_simple_solve.

**Comment by hpohekar** [comment] 2024-10-23 08:04
@seanpearsonuk @tejalprabhu01 

Steps to reproduce this issue are incomplete.

![image](https://github.com/user-attachments/assets/674b27bc-c62c-4ca0-b65a-4e68f354fd6c)

```
>>> import ansys.fluent.core as pyfluent
>>> fluent_session = pyfluent.launch_fluent()
>>> fluent_session.settings.file.read(file_type="case", file_name=r"C:\Users\hpohekar\Downloads\StaticMixer__unitless.cas\Design0001\StaticMixer_unitless.cas.h5")
Fast-loading "D:\ANSYSDev\vNNN\fluent\fluent25.1\\addons\afd\lib\hdfio.bin"
Done.
Multicore SMT processors detected. Processor affinity set!

Reading from AAPQ13pUvWxQtxN:"C:\Users\hpohekar\Downloads\StaticMixer__unitless.cas\Design0001\StaticMixer_unitless.cas.h5" in NODE0 mode ...
  Reading mesh ...
       56042 cells,     1 cell zone  ...
          56042 polyhedra cells,  zone id: 384
      373979 faces,     5 face zones ...
         357911 polygonal interior faces,  zone id: 383
          14725 polygonal wall faces,  zone id: 17
            646 polygonal pressure-outlet faces,  zone id: 20
            646 polygonal velocity-inlet faces,  zone id: 19
             51 polygonal velocity-inlet faces,  zone id: 18
      300760 nodes,     1 node zone  ...
Warning: reading 2 partition grid onto 1 compute node machine.
         Combining every 2 partitions.
  Done.


Building...
     mesh
     materials,
     interface,
     domains,
        mixture
     zones,
        interior--volume-volume
        volume-volume:1
        outlet
        inlet_main
        inlet_side
        volume-volume
     parallel,
Done.
>>> fluent_session.settings.parameters.input_parameters.expression[name] = {"value" : value}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'value' is not defined. Did you mean: 'False'?
>>>     
```

**Comment by hpohekar** [comment] 2024-10-23 08:20
@seanpearsonuk @tejalprabhu01 

If I use a random value I get another error as follows:

![image](https://github.com/user-attachments/assets/253936b4-f704-40fd-8534-1e2966b3f817)

**but apart from that I can confirm that following code triggers the inactive gRPC error and it is coming from `scheme_eval` service.**

```
>>> fluent_session.settings.parameters.output_parameters.list()

      Parameter Name           Value            Unit
----------------------------------------------------
temp-outlet-uniformity-op               0            (#f)
temp-outlet-average-op               0 (temperature #f)
temp-outlet-stdev-op               0 (temperature #f)
Error: CDR: invalid argument [1]: wrong type [not a pair]
Error Object: #f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 1780, in __call__
    return self.execute_command(**kwds)
  File "D:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 1726, in execute_command
    ret = self._execute_command(*args, **scmKwds)
  File "D:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 1711, in _execute_command
    ret = _fix_parameter_list_return(ret)
  File "D:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 1760, in _fix_parameter_list_return
    unit_labels = _fix_parameter_list_return.scheme_eval(
  File "D:\pyfluent\src\ansys\fluent\core\services\scheme_eval.py", line 343, in scheme_eval
    return self.eval(val)
  File "D:\pyfluent\src\ansys\fluent\core\services\scheme_eval.py", line 273, in eval
    response = self.service.scheme_eval(request)
  File "D:\pyfluent\src\ansys\fluent\core\services\scheme_eval.py", line 76, in scheme_eval
    return self.__stub.SchemeEval(request, metadata=self.__metadata)
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_channel.py", line 440, in result
    raise self
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_channel.py", line 440, in result
    raise self
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_channel.py", line 440, in result
    raise self
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_channel.py", line 1198, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "D:\pyfluent\.venv\lib\site-packages\grpc\_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "An error occurred in the server while evaluating the Scheme expression"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"An error occurred in the server while evaluating the Scheme expression", grpc_status:2, created_time:"2024-10-23T08:15:01.0044441+00:00"}"
>
>>>
```

**Comment by tejalprabhu01** [comment] 2024-10-23 08:25
@hpohekar , You can also skip that step. I just gave a general idea of command that was used. The "name" was ofcourse name of the one of the input parameter and "value" was some value.

For eg: fluent_session.settings.parameters.input_parameters.expression["inlet_main_temp"] = {"value" : 300.0}
fluent_session.settings.parameters.input_parameters.expression["side2main_v_ratio"] = {"value" : 2.0}

**Comment by mkundu1** [comment] 2024-10-25 00:25
@tejalprabhu01 The PyFluent side fix for this issue will go in in the next version. Can you please apply the following patch in 25.1 optiSLang code:
```
# Patching flobject._fix_parameter_list_return to handle unitless quantities
from ansys.fluent.core.solver import flobject
def _fix_parameter_list_return(val):
    if isinstance(val, dict):
        new_val = {}
        for name, v in val.items():
            value, units = v
            if len(units) > 0 and isinstance(units[0], str):
                unit_labels = _fix_parameter_list_return.scheme_eval(
                    f"(units/inquire-available-label-strings-for-quantity '{units[0]})"
                )
                unit_label = unit_labels[0] if len(unit_labels) > 0 else ""
            else:
                unit_label = ""
            new_val[name] = [value, unit_label]
        return new_val
    return val
flobject._fix_parameter_list_return = _fix_parameter_list_return

import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent()
solver.settings.file.read_case(file_name="StaticMixer_unitless.cas.h5")
print(solver.settings.parameters.output_parameters.list())
```

**Comment by seanpearsonuk** [comment] 2024-10-25 10:55
@mkundu1 Are we patching Fluent similarly?

**Closed** 2024-10-25 11:50 UTC
Labels: bug, optiSLang
