### ISSUE TITLE
dubious exception handling in _get_running_session_mode

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1774] opened 2023-07-07 12:54 UTC
```
        except BaseException:
            raise RuntimeError("Fluent session password mismatch")
```
- How do we know that that is the error? 
- Either raise `from` the original exception, or catch it, log it and re-raise it, or just don't catch it.

**Comment by raph-luc** [comment] 2023-07-07 18:07
Duplicate of the more general https://github.com/ansys/pyfluent/issues/1778

**Closed by raph-luc** 2023-07-07 18:07 UTC
Labels: bug
