### ISSUE TITLE
Bug located in ... flobject.py

### ISSUE THREAD

**Issue by prmukherj** [ansys/pyfluent#2476] opened 2024-02-20 14:13 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

1.
>>> x = s.setup.boundary_conditions.velocity_inlet["inlet1"].turbulence
x.turbulent_intensity()   
0.05
>>> x.turbulent_intensity.__class__.__bases__
(<class 'ansys.fluent.core.solver.flobject.Real'>, <class 'ansys.fluent.core.solver.flobject._HasAllowedValuesMixin'>)
 
2.
>>>AttributeError: value_with_units is not an allowed Settings objects name.

Update the message to be more generic.

### 📝 Steps to reproduce

x = s.setup.boundary_conditions.velocity_inlet["inlet1"].turbulence
x.turbulent_intensity.__class__.__bases__

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
.
```

**Comment by mkundu1** [comment] 2024-02-22 17:14
Cannot reproduce with the latest Fluent 24.2, I think the issue is recently fixed in Fluent.

**Closed by mkundu1** 2024-02-22 17:14 UTC
Labels: bug, enhancement
