### ISSUE TITLE
parameters.output_parameters.list() returns None

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2587] opened 2024-03-19 15:33 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

Unable to get the list of output parameters with parameters.output_parameters.list(). It used to work previously.
![image](https://github.com/ansys/pyfluent/assets/97435870/8868511b-2317-4ce5-a313-6f67b123176a)

@seanpearsonuk @mainakk 

### 📝 Steps to reproduce

session = pyfluent.launch_fluent(version="2d", mode="solver", start_watchdog=False)
session.file.read(file_type="case", file_name=r"nozzle-2D-WB.cas.h5")
op = session.parameters.output_parameters.list()
for n, v in op.items():
     print(n)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
from ansys cpython 3.10.12.2 conan package - 0.20.dev9
```

**Comment by tejalprabhu01** [comment] 2024-03-21 09:14
@seanpearsonuk @mainakk Can we please get this bug fix for 24.2? The Fluent nodes are broken at the moment due to the broken command

**Comment by seanpearsonuk** [comment] 2024-03-21 09:26
@mkundu1 I'm holding off looking at this as I see that you have self-assigned it.

**Comment by mkundu1** [comment] 2024-03-21 11:29
@seanpearsonuk @tejalprabhu01 The issue is fixed in Fluent code. We can create a PyFluent package with the fix (updated generated API files) after the certified Fluent build/image is available.

**Comment by optislangdeveloper** [comment] 2024-03-25 14:40
> @seanpearsonuk @tejalprabhu01 The issue is fixed in Fluent code. We can create a PyFluent package with the fix (updated generated API files) after the certified Fluent build/image is available.

What's the timeline for that?

**Comment by mkundu1** [comment] 2024-03-25 14:50
@optislangdeveloper The latest certified build doesn't contain the Fluent side fix, hopefully it will be available in the next build. We will create a PyFluent package from that build. cc: @seanpearsonuk @tejalprabhu01

**Comment by mkundu1** [comment] 2024-03-27 12:50
@optislangdeveloper @tejalprabhu01 The Fluent image with the fix is now available, we'll perpare a pyfluent build with the fix soon.

**Closed** 2024-03-28 12:35 UTC
Labels: bug, Fluent, optiSLang
