### ISSUE TITLE
solver.tui.define.models.viscous.geko_options()  is not callable

### ISSUE THREAD

**Issue by etiennelame** [ansys/pyfluent#2315] opened 2023-12-14 01:37 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

can not use the command to set geko parameter.
solver.tui.define.models.viscous.geko_options()
Traceback (most recent call last):

  Cell In[3], line 1
    solver.tui.define.models.viscous.geko_options()

TypeError: 'geko_options' object is not callable

### 📝 Steps to reproduce

solver.tui.define.models.viscous.kw_geko('yes')
solver.tui.define.models.viscous.geko_options()

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2022R2

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.19
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.18.2
ansys-fluent-parametric==0.9.0
ansys-fluent-visualization==0.8.0
ansys-platform-instancemanagement==1.1.2
```

**Comment by ansjsia** [comment] 2023-12-15 14:45
@etiennelame `geko_options` is a `TUIMenu` object and so cannot be called because it is not a command. To change the GEKO model options, you need to call one of the commands that is a child of the `TUIMenu`. For example, something like `geko_options.blending_function('yes', 'no')` can be called to set blending functions for the GEKO model.

If you wanted to know what options are available in the `geko_options` menu, you can launch Fluent with `show_gui=True` to access the TUI directly or call `dir(solver.tui.define.models.viscous.geko_options)`.

**Comment by etiennelame** [comment] 2023-12-19 10:37
In fact, i want to change the parameter "csep" of geko model.

The command " solver.tui.define.models.viscous.geko_options.csep("y",1.1)" is used.

Normally it should be written as "solver.tui.define.models.viscous.geko_options.csep(1.1)", but it cannot work without the "y".

Is that a bug or it should work with "y"?

**Comment by etiennelame** [comment] 2023-12-19 10:41
> In fact, i want to change the parameter "csep" of geko model.
> 
> The command " solver.tui.define.models.viscous.geko_options.csep("y",1.1)" is used.
> 
> Normally it should be written as "solver.tui.define.models.viscous.geko_options.csep(1.1)", but it cannot work without the "y".
> 
> Is that a bug or it should work with "y"?

I have figured out that the tui command should work "y" to choose whether using constant or expression. so, "y"should be added

**Comment by ansjsia** [comment] 2023-12-19 15:24
@etiennelame Yes, you need to enter `y` or `yes` to proceed to the next step in the TUI command. PyFluent follows this behavior.

**Comment by ansjsia** [comment] 2023-12-19 15:25
Closed as this is not a bug.

**Closed by ansjsia** 2023-12-19 15:25 UTC
Labels: bug
