### ISSUE TITLE
In Fluent Meshing, recording python journal when save mesh file instead saves fmd file

### ISSUE THREAD

**Issue by rploconnor** [ansys/pyfluent#1986] opened 2023-09-15 14:11 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Recording journal of the action of saving an msh.gz file records the following command:

PartManagement.SaveFmdFile(FilePath=r'E:/test_workflow_files\test.fmd')

It should instead save it as an msh.gz file.

### 📝 Steps to reproduce

Record a journal including the operation of saving a mesh file.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
aiohttp==3.8.4
aiosignal==1.3.1
ansys-api-fluent==0.3.12
ansys-api-geometry==0.2.11
ansys-api-mapdl==0.5.1
ansys-api-mechanical==0.1.0
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-api-pyensight==0.2.2
ansys-api-systemcoupling==0.1.0
ansys-dpf-core==0.8.1
ansys-dpf-gate==0.3.1
ansys-dpf-gatebin==0.3.1
ansys-dynamicreporting-core==0.4.0
ansys-fluent-core==0.17.dev1
ansys-fluent-visualization==0.8.dev1
-e git+https://github.com/ansys/pygeometry@5853e7a4d7dadbec02c3c06f95a65e920860ff10#egg=ansys_geometry_core
ansys-grpc-dpf==0.7.1
ansys-mapdl-core==0.65.2
ansys-mapdl-reader==0.52.20
ansys-mechanical-core==0.9.2
ansys-meshing-prime==0.4.0.dev9
ansys-platform-instancemanagement==1.1.1
ansys-pyensight-core==0.4.1.dev0
ansys-pythonnet==3.1.0rc1
ansys-systemcoupling-core==0.2.0
ansys-tools-path==0.3.1
ansyscodefest @ file:///E:/PYTHON/CornellCodeFest/ansyscodefest-0.0.62-py3-none-any.whl#sha256=88b8736c067cd41d78b3c28d179722a8f3891ca75a42fc614890a33a2a1830f3
anyio==3.7.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asgiref==3.7.2
asttokens==2.2.1
async-lru==2.0.2
async-timeout==4.0.2
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beartype==0.14.1
beautifulsoup4==4.12.2
bleach==6.0.0
bokeh==3.2.1
build==0.10.0
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
Choco==1.0.5
click==8.1.7
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
Django==4.2.3
docker==6.1.3
docutils==0.20.1
exceptiongroup==1.1.2
executing==1.2.0
fastjsonschema==2.17.1
filelock==3.12.2
fonttools==4.41.0
fqdn==1.5.1
frozenlist==1.4.0
geomdl==5.3.1
google-api-core==2.11.1
google-api-python-client==2.93.0
google-auth==2.22.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.59.1
grpcio==1.56.0
grpcio-health-checking==1.48.2
grpcio-status==1.48.2
h5py==3.9.0
httplib2==0.22.0
idna==3.4
importlib-metadata==6.7.0
ipykernel==6.24.0
ipython==8.10.0
ipython-genutils==0.2.0
ipywidgets==8.0.7
isoduration==20.11.0
jaraco.classes==3.3.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.23.0
keyring==24.2.0
kiwisolver==1.4.4
linkify-it-py==2.0.2
lxml==4.9.2
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.6.3
matplotlib-inline==0.1.6
mdit-py-plugins==0.4.0
mdurl==0.1.2
mistune==3.0.1
more-itertools==9.1.0
multidict==6.0.4
nbclient==0.8.0
nbconvert==7.6.0
nbformat==5.9.0
nest-asyncio==1.5.6
notebook==7.0.3
notebook_shim==0.2.3
numpy==1.25.0
overrides==7.3.1
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
panel==1.2.0
param==1.13.0
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
Pint==0.22
pkginfo==1.9.6
platformdirs==3.8.0
pluggy==1.2.0
pooch==1.7.0
prettyprint==0.1.5
prometheus-client==0.17.0
prompt-toolkit==3.0.39
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.5
pure-eval==0.2.2
pyansys-docker==5.0.4
pyansys-tools-versioning==0.4.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.15.1
pyiges==0.3.1
pyparsing==3.0.9
pypng==0.20220715.0
pyproject-api==1.5.3
pyproject_hooks==1.0.0
pyrsistent==0.19.3
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
pyvista==0.40.1
pyvistaqt==0.11.0
pyviz-comms==2.3.2
pywin32==306
pywin32-ctypes==0.2.2
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.4.0
readme-renderer==40.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rfc3986==2.0.0
rfc3986-validator==0.1.1
rich==13.4.2
rsa==4.9
scipy==1.11.1
scooby==0.7.2
Send2Trash==1.8.2
shiboken6==6.5.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
sqlparse==0.4.4
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.2
tox==4.6.4
tqdm==4.65.0
traitlets==5.9.0
trame==2.5.0
trame-client==2.9.4
trame-components==2.1.1
trame-deckgl==2.0.2
trame-markdown==2.0.2
trame-matplotlib==2.0.2
trame-plotly==2.1.1
trame-rca==0.3.1
trame-router==2.0.2
trame-server==2.11.4
trame-simput==2.3.2
trame-vega==2.0.3
trame-vtk==2.5.4
trame-vuetify==2.2.4
twine==4.0.2
typing==3.7.4.3
typing_extensions==4.7.1
tzdata==2023.3
uc-micro-py==1.0.2
uri-template==1.3.0
uritemplate==4.1.1
urllib3==1.26.16
virtualenv==20.23.1
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
widgetsnbextension==4.0.8
wslink==1.11.1
xyzservices==2023.7.0
yarl==1.9.2
zipp==3.15.0
```

**Comment by seanpearsonuk** [comment] 2023-09-19 14:48
@rploconnor is there an attached script?

**Comment by raph-luc** [comment] 2023-09-19 15:33
Sounds like a Fluent server issue and not PyFluent?

The new Fluent meshing datamodel exposure for file operations might help with this, depending on what exactly the issue is. Will see if I can reproduce this locally (a script would certainly help).

**Comment by raph-luc** [comment] 2023-10-31 16:13
This is indeed a server-side issue, going to debug this as I can find the time

**Comment by seanpearsonuk** [comment] 2024-05-01 09:39
> This is indeed a server-side issue, going to debug this as I can find the time

@raph-luc Does that mean you have a script to reproduce?

**Comment by raph-luc** [comment] 2024-05-01 13:19
@seanpearsonuk sorry, I should've written more details down. 

No script necessary as this is a server-side issue and not related to PyFluent: just start up Fluent (can be 2023 R2 as reported here or newer), either load an existing mesh or e.g. initialize a WTM workflow and at least import a geometry, then start recording a Python journal, and use the file menu to write a mesh file. Finally, check the journal file and see that the wrong command was recorded.

Tested just now with 2024 R2 and it seems to save `workflow.SaveWorkflow(FilePath=r'C:/Tests/mesh_workflow_files\mesh.wft')` instead which is still not what we want.

I am thinking we should close this issue here in the PyFluent repo, and create a Fluent issue tracker for this. Should I go ahead and do that?

**Comment by seanpearsonuk** [comment] 2024-05-01 13:46
create a Fluent issue tracker for this. Should I go ahead and do that?
- Yes, please. That will save me working through it and duplicating your effort. Thanks very much.

I am thinking we should close this issue here in the PyFluent repo
- Generally we keep the PyFluent issues open until the child issue is closed. I normally write the Fluent ID in a comment. I realise that it's heavyweight but it has advantages too.

**Comment by raph-luc** [comment] 2024-05-01 15:02
Fluent issue tracker 1035421

**Closed** 2024-10-18 20:55 UTC
Labels: bug, Fluent, workflow API
