### ISSUE TITLE
cwd argument in launch_fluent gives uninteded warning

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2633] opened 2024-03-29 15:00 UTC
```
>>> solver = pyfluent.launch_fluent(cwd=r"d:\work")
pyfluent.launcher WARNING: These specified arguments are only supported when starting local standalone Fluent clients: cwd.
```

**Comment by mkundu1** [comment] 2024-04-10 17:27
@hpohekar Can you please look into this too as a part of the launcher code improvement. There might be more arguments for hich such unexpected warnigns are coming.
cc: @prmukherj

**Comment by hpohekar** [comment] 2024-04-11 03:28
Yes, sure.

**Comment by hpohekar** [comment] 2024-04-11 07:56
@mkundu1 @seanpearsonuk 

As we are specifying in above code that `env, cwd, topy, case_file_name, lightweight_mode, journal_file_names, case_data_file_name` are valid for only Standalone mode then should we remove them from constructor signature of PIM and Container mode ?

**Comment by hpohekar** [comment] 2024-04-12 04:52
Closing because not able to reproduce.

**Comment by hpohekar** [comment] 2024-04-12 12:07
I'm getting this warning now.

![image](https://github.com/ansys/pyfluent/assets/106588300/c58f699b-bfee-442c-8ae8-adeef6484b64)

**Comment by hpohekar** [comment] 2024-04-12 12:09
@mkundu1 @seanpearsonuk 

I think we have already removed arguments that are supported for Standalone mode only from constructors of PIM and Container launcher so maintaining this code and raising this warning is redundant.

I think we shall remove this code and warning.

Shall we remove this code now ?

**Comment by hpohekar** [comment] 2024-04-17 06:24
@mkundu1 

I have tried to reproduce this issue on my and @prmukherj 's system (with latest changes) but it is not reproducible. Therefore closing this now.

**Comment by hpohekar** [comment] 2024-04-17 06:25
@mkundu1 

I have tried to reproduce this issue on my and @prmukherj 's system (with latest changes) but it is not reproducible. Therefore closing this now.

**Closed by hpohekar** 2024-04-17 06:25 UTC
