### ISSUE TITLE
Not able to open the fluent remotely from python flask web app

### ISSUE THREAD

**Issue by pavankumarkonchada** [ansys/pyfluent#1929] opened 2023-08-29 10:08 UTC
Hi Team, 
             I am not able to execute the command  "pyfluent.launch_fluent(precision="double", processor_count=4, mode="meshing",show_gui =True)"  on virtual machine from python flask web app. But when I do it manually on virtual machine fluent meshing is getting opened.  Please suggest me a way to execute the command through web app on any machine. Also I have tried by keeping show_gui= False also. Nothing worked out

**Comment by mkundu1** [comment] 2023-08-29 13:04
@pavankumarkonchada Can you please share the code of a minimal reproducible example?

**Comment by pavankumarkonchada** [comment] 2023-08-29 13:06
from flask import Flask
import os
import paramiko

app = Flask(__name__)

@app.route('/')
def launch_fluent():
    vm_ip_address = '13.68.168.34'
    username = 'pavan'
    password = 'Cadfemindia@2023'
    ansys_fluent_path = 'C:\\Program Files\\ANSYS Inc\\ANSYS Student\\v231\\fluent\\ntbin\\win64'
    command_to_execute = f'python -c "from ansys.fluent.core import launch_fluent;import ansys.fluent.core as pyfluent;pyfluent.launch_fluent(precision=\'double\', processor_count=4, mode=\'meshing\', show_gui=True)"'

    try:
        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh_client.connect(vm_ip_address, username=username, password=password)

        # Execute the Fluent launch command on remote VM
        command_with_path = f'setx PATH "%PATH%;{ansys_fluent_path}" && {command_to_execute}'
        stdin, stdout, stderr = ssh_client.exec_command(command_with_path)

        # Capture and process output
        output = stdout.read().decode()
        error = stderr.read().decode()

        paramiko.util.log_to_file('sssh.log')
        ssh_client.close()

        return f"<pre>Output: {output}\nError: {error}</pre>"
    except Exception as e:
        app.logger.error(f'Error occurred: {e}')
        return f'Error: {e}'

if __name__ == '__main__':
    app.run(debug=True)          


When I try to execute the above code from azure app service to azure virtual machine . I am getting this erro
Output: 
SUCCESS: Specified value was saved.

Error: Traceback (most recent call last):
  File "", line 1, in 
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 593, in launch_fluent
    launch_string = _generate_launch_string(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 407, in _generate_launch_string
    exe_path = get_fluent_exe_path(**argvals)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 111, in get_fluent_exe_path
    ansys_version = get_ansys_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 74, in get_ansys_version
    raise RuntimeError("No ANSYS version can be found.")
RuntimeError: No ANSYS version can be found.

**Comment by mkundu1** [comment] 2023-08-29 13:13
From the error message, it looks like the AWP_ROOT environment variable is not set on the machine where `launch_fluent` is executed.

**Comment by pavankumarkonchada** [comment] 2023-08-29 13:16
But I am to execute the same python flask successfully running on the machine locally. Instead of using appservice

**Comment by raph-luc** [comment] 2023-08-29 13:22
@pavankumarkonchada Try something like this to set the environment variable:
```
# Execute the Fluent launch command on remote VM
env={'AWP_ROOT231': 'C:\Program Files\ANSYS Inc\ANSYS Student\v231'}
command_with_path = f'setx PATH "%PATH%;{ansys_fluent_path}" && {command_to_execute}'
stdin, stdout, stderr = ssh_client.exec_command(command_with_path, environment=env)
```

Also, I think you may be able to remove the %PATH% you included there, but try this first to see if PyFluent is now capable of finding where Fluent is.

**Comment by pavankumarkonchada** [comment] 2023-08-29 13:40
The issue still persists even after modifying as per your suggestion, and yes the path you have mentioned is where fluent is in the machine

**Comment by pavankumarkonchada** [comment] 2023-08-29 13:43
And I have tried to modify the launcher.py with directly mentioning the fluent root path, at that time Iam getting as below
Output:
SUCCESS: Specified value was saved.

Error:
WARNING: The data being saved is truncated to 1024 characters.

**But still fluent is not opening**, so i have reverted the file to its original

**Comment by pavankumarkonchada** [comment] 2023-08-30 06:51
Now the fluent launcher is opening but when I try to load the geometry it is giving the below error
Output: 
SUCCESS: Specified value was saved.

Error: 
WARNING: The data being saved is truncated to 1024 characters.
Traceback (most recent call last):
  File "", line 1, in 
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\datamodel_se.py", line 1021, in __call__
    response = self.service.execute_command(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:50922: Connection refused

**Comment by pavankumarkonchada** [comment] 2023-08-30 06:52
This is the syntax I am using

from flask import Flask
import paramiko

app = Flask(__name__)

@app.route('/')
def launch_fluent():
    try:
        vm_ip_address = '13.68.168.34'
        username = 'pavan'
        password = 'Cadfemindia@2023'
        
        ansys_fluent_path = r'C:\\Program Files\\ANSYS Inc\\ANSYS Student\\v231\\fluent\\ntbin\\win64'
        command_to_execute = (
            f'setx PATH "%PATH%;{ansys_fluent_path}" && '
            r'cmd /C C:\\Users\\pavan\\AppData\\Local\\Programs\\Python\\Python311\\python.exe '
            '-c "from ansys.fluent.core import launch_fluent;'
            'import ansys.fluent.core as pyfluent;'
            'meshing=pyfluent.launch_fluent(precision=\'double\', processor_count=4, mode=\'meshing\', show_gui=False);'
            'meshing.workflow.InitializeWorkflow(WorkflowType=\'Watertight Geometry\');'
            'path=r\\"C:\\\\check\\\\geom1.scdoc\\";'
            'meshing.workflow.TaskObject[\\"Import Geometry\\"].Arguments = {"FileName": path,"LengthUnit": "mm",}"'
        )

        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh_client.connect(vm_ip_address, username=username, password=password)

        # Execute the Fluent launch command on remote VM
        stdin, stdout, stderr = ssh_client.exec_command(command_to_execute)

        # Capture and process output
        output = stdout.read().decode()
        error = stderr.read().decode()

        ssh_client.close()

        return f"<pre>Output: {output}\nError: {error}</pre>"
    except Exception as e:
        app.logger.error(f'Error occurred: {e}')
        return f'Error: {e}'

if __name__ == '__main__':
    app.run(debug=True)

**Comment by pavankumarkonchada** [comment] 2023-08-30 12:08
"RuntimeError: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:50922: Connection refused"  

it is trying to connect to random ports on virtual machine which are not even available. Please suggest me how to restrict it connect to ports which are available.

**Comment by pavankumarkonchada** [comment] 2023-08-30 12:41
Where to give this environment variables

**Comment by mkundu1** [comment] 2023-08-30 12:57
This should be set to the Fluent process. So, you can either set it on the machine where Fluent is being launched or use  `launch_fluent` to set it to the Fluent process.
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent(show_gui=True, env={"REMOTING_PORTS":"28055/portspan=2"})
```

**Comment by pavankumarkonchada** [comment] 2023-08-30 13:17
Hi Mukundu1, 
         Even the port (65530) mentioned by me is available it is throwing the same error. 

**Output: 
SUCCESS: Specified value was saved.

Error: 
WARNING: The data being saved is truncated to 1024 characters.
Traceback (most recent call last):
  File "C:\mixingtank_pyfluent.py", line 13, in 
    meshing.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\datamodel_se.py", line 1021, in __call__
    response = self.service.execute_command(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:65530: Connection refused**

**Comment by mkundu1** [comment] 2023-08-30 13:59
https://github.com/ansys/pyfluent/discussions/1894 is from the `launch_fluent` step. So, that would be a different issue (I'm still trying to understand the root cause).

**Comment by pavankumarkonchada** [comment] 2023-08-30 14:02
Execution of the line solver.tui.report.system.time_stats() while opening fluent in solver mode using launch_fluent() results in the following error 
Output: 
SUCCESS: Specified value was saved.

Error: 
WARNING: The data being saved is truncated to 1024 characters.
Traceback (most recent call last):
  File "C:\mixingtank_pyfluent.py", line 19, in 
    solver.tui.report.system.time_stats()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\datamodel_tui.py", line 278, in __getattribute__
    if PyMenu(self.service, path).get_child_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\datamodel_tui.py", line 157, in get_child_names
    response = self._service.get_attribute_value(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python311\Lib\site-packages\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:65530: Connection refused

**Comment by mkundu1** [comment] 2023-08-30 14:20
It is strange that the health_check within launch_fluent which also makes a remote call is getting passed but subsequent remote calls are failing.

Just to give it a try, can you please set `pyfluent.INFER_REMOTING_IP = False` before `launch_fluent`?

**Comment by pavankumarkonchada** [comment] 2023-08-30 14:28
including pyfluent.INFER_REMOTING_IP = False before launch_fluent results in the same error mentioned before.

**Comment by mkundu1** [comment] 2023-08-30 14:41
As a workaround, can you try launching Fluent in the VM and then connecting from PyFluent using `connect_to_fluent`? You can use the command line launch option `-sifile` to start the server in meshing mode
```
C:\Program Files\ANSYS Inc\ANSYS Student\v231\fluent\ntbin\win64\fluent.exe -meshing -sifile="server_info.txt"
```

`connect_to_fluent` doc - https://fluent.docs.pyansys.com/version/stable/api/general/launcher/index.html#ansys.fluent.core.launcher.launcher.connect_to_fluent

**Comment by mkundu1** [comment] 2023-08-30 15:05
I thought Fluent was getting launched correctly. The error message means that Fluent crashes after launching. Are you able to launch Fluent through the command line? You can launch it without GUI:
```
C:\Program Files\ANSYS Inc\ANSYS Student\v231\fluent\ntbin\win64\fluent.exe -meshing -gu
```

**Comment by pavankumarkonchada** [comment] 2023-08-30 16:54
Yes on executing the above command fluent meshing is  getting opened

**Comment by mkundu1** [comment] 2023-08-30 17:52
Can you still try the `connect_to_fluent` method to connect to the launched session? Note that both Fluent and PyFluent should be started on the remote machine.

**Comment by mkundu1** [comment] 2023-08-30 17:57
> Yes on executing the above command fluent meshing is getting opened

I assume that this is working on the remote machine (executed via `ssh_client.exec_command` as in your original script)

**Comment by pavankumarkonchada** [comment] 2023-08-31 06:19
Yes, Fluent is opening on my remote machine when executed via ssh_client.exec_command() as you mentioned. I am unable to use connect_to_fluent to establish connection to fluent session launched through gui. I am getting an error stating module 'ansys.fluent.core' has no attribute 'connect_to_fluent'.

**Comment by pavankumarkonchada** [comment] 2023-08-31 07:40
> > Yes on executing the above command fluent meshing is getting opened
> 
> I assume that this is working on the remote machine (executed via `ssh_client.exec_command` as in your original script)

Yes the fluent meshing session is getting opened when trying to connect through ssh_client.exec_command. Fluent session is opened tasking manager

**Comment by pavankumarkonchada** [comment] 2023-08-31 09:57
It is only showing fluent start up screen but not entering into fluent session

**Comment by pavankumarkonchada** [comment] 2023-08-31 11:08
I have tried also running python flask application which executes the fluent command on local machine to connect to other local machine as server (both are in same lan) in that case also fluent is launching and closing saying abnormal exit.   So hopefully it is not the issue with the cloud. Please suggest me why it is exiting

**Comment by pavankumarkonchada** [comment] 2023-08-31 11:09
These are the  contents of two error files
Error [node 0] [time 8/31/23 16:35:16] Abnormal Exit!
Error [node 999999] [time 8/31/23 16:35:16] Abnormal Exit!

**Comment by mkundu1** [comment] 2023-08-31 15:47
`connect_to_fluent` is available since 0.16, for earlier releases `launch_fluent(start_instance=False, ...)` will work.

Fluent processes seem to be crashing at startup, it is difficult to tell why from the error messages. Is there any .trn file created? It could be due to some installation issue; you can try reinstalling Fluent.

**Comment by raph-luc** [comment] 2023-08-31 16:09
Try also `cleanup_on_exit=False` argument for `launch_fluent`, see if that changes anything when using PyFluent to launch Fluent

And definitely use the latest PyFluent version

**Comment by pavankumarkonchada** [comment] 2023-09-05 09:57
I am able to solve the issue by adding -ssh in the additional argument

**Comment by raph-luc** [comment] 2023-09-05 13:31
That is interesting, `-ssh` should be the default in my understanding (since Fluent 2015)

Thank you for letting us know how you solved it, closing this issue

**Closed by raph-luc** 2023-09-05 13:31 UTC
