### ISSUE TITLE
launch_fluent blocks further interaction

### ISSUE THREAD

**Issue by g-pagliuca** [ansys/pyfluent#2010] opened 2023-09-22 14:45 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I start fluent with `launch_fluent` (with the show GUI option) the GUI pops up and I can use it but the jupyter cell is in execution and I cannot go forward

### 📝 Steps to reproduce

```
import ansys.fluent.core as pyfluent
solver_session = pyfluent.launch_fluent(mode="solver", show_GUI=True)
```

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

2022R1 and 2023R1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
aiofiles @ file:///croot/aiofiles_1683773582346/work
aiosqlite @ file:///croot/aiosqlite_1683773899903/work
ansys-api-fluent==0.3.12
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.15.0
ansys-platform-instancemanagement==1.1.1
anyio @ file:///work/ci_py311/anyio_1676823771847/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///work/ci_py311/argon2-cffi-bindings_1676823553406/work
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
attrs @ file:///work/ci_py311/attrs_1676822758931/work
Babel @ file:///work/ci_py311/babel_1676825020543/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///croot/beautifulsoup4-split_1681493039619/work
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
brotlipy==0.7.0
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi @ file:///work/ci_py311/cffi_1676822533496/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
comm @ file:///work/ci_py311/comm_1677709131612/work
contourpy @ file:///work/ci_py311/contourpy_1676827066340/work
cryptography @ file:///croot/cryptography_1694444244250/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
entrypoints @ file:///work/ci_py311/entrypoints_1676823319002/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fastjsonschema @ file:///work/ci_py311_2/python-fastjsonschema_1679340124475/work
fonttools==4.25.0
googleapis-common-protos==1.59.1
grpcio==1.56.0
h5py==3.9.0
idna @ file:///work/ci_py311/idna_1676822698822/work
importlib-metadata==6.7.0
ipykernel @ file:///croot/ipykernel_1691121631942/work
ipython @ file:///croot/ipython_1694181358621/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///croot/ipywidgets_1679394798311/work
jedi @ file:///work/ci_py311_2/jedi_1679336495545/work
Jinja2 @ file:///work/ci_py311/jinja2_1676823587943/work
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///croot/jsonschema_1678983421637/work
jupyter @ file:///work/ci_py311/jupyter_1676837039433/work
jupyter-console @ file:///croot/jupyter_console_1679999630278/work
jupyter-events @ file:///croot/jupyter_events_1684268042853/work
jupyter-server @ file:///work/ci_py311/jupyter_server_1676824947163/work
jupyter-ydoc @ file:///croot/jupyter_ydoc_1683747223142/work
jupyter_client @ file:///work/ci_py311/jupyter_client_1676823491351/work
jupyter_core @ file:///croot/jupyter_core_1679906564508/work
jupyter_server_fileid @ file:///croot/jupyter_server_fileid_1684273577568/work
jupyter_server_ydoc @ file:///croot/jupyter_server_ydoc_1686767404829/work
jupyterlab @ file:///croot/jupyterlab_1686179668131/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets @ file:///croot/jupyterlab_widgets_1679055282532/work
jupyterlab_server @ file:///croot/jupyterlab_server_1680792501448/work
kiwisolver @ file:///work/ci_py311/kiwisolver_1676827230232/work
lxml==4.9.2
MarkupSafe @ file:///work/ci_py311/markupsafe_1676823507015/work
matplotlib @ file:///croot/matplotlib-suite_1693812469450/work
matplotlib-inline @ file:///work/ci_py311/matplotlib-inline_1676823841154/work
mistune @ file:///work/ci_py311/mistune_1676823698136/work
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
msgpack-python==0.5.6
munkres==1.1.4
nbclassic @ file:///croot/nbclassic_1681756170010/work
nbclient @ file:///work/ci_py311/nbclient_1676823713954/work
nbconvert @ file:///work/ci_py311/nbconvert_1676823854564/work
nbformat @ file:///croot/nbformat_1694616755618/work
nest-asyncio @ file:///work/ci_py311/nest-asyncio_1676823382924/work
notebook @ file:///croot/notebook_1690984815942/work
notebook_shim @ file:///work/ci_py311/notebook-shim_1676825053954/work
numpy @ file:///croot/numpy_and_numpy_base_1691091611330/work
packaging @ file:///croot/packaging_1693575174725/work
pandas==2.0.3
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///croot/pillow_1695134008276/work
platformdirs @ file:///croot/platformdirs_1692205439124/work
ply==3.11
prometheus-client @ file:///work/ci_py311_2/prometheus_client_1679340520168/work
prompt-toolkit @ file:///work/ci_py311/prompt-toolkit_1676824857154/work
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil @ file:///work/ci_py311_2/psutil_1679337388738/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyfluent==0.2.1
Pygments @ file:///croot/pygments_1684279966437/work
pyOpenSSL @ file:///croot/pyopenssl_1690223430423/work
pyparsing @ file:///work/ci_py311/pyparsing_1677811559502/work
PyQt5-sip==12.11.0
pyrsistent @ file:///work/ci_py311/pyrsistent_1676823088752/work
PySocks @ file:///work/ci_py311/pysocks_1676822712504/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-json-logger @ file:///croot/python-json-logger_1683823803357/work
pytz @ file:///croot/pytz_1695131579487/work
PyYAML @ file:///work/ci_py311/pyyaml_1676827445582/work
pyzmq @ file:///work/ci_py311/pyzmq_1676918885689/work
qtconsole @ file:///croot/qtconsole_1681394213385/work
QtPy @ file:///work/ci_py311/qtpy_1676827467989/work
requests @ file:///croot/requests_1690400202158/work
rfc3339-validator @ file:///croot/rfc3339-validator_1683077044675/work
rfc3986-validator @ file:///croot/rfc3986-validator_1683058983515/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sip @ file:///work/ci_py311/sip_1676825117084/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio @ file:///work/ci_py311/sniffio_1676823742530/work
soupsieve @ file:///croot/soupsieve_1680518478486/work
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
terminado @ file:///work/ci_py311/terminado_1677696151350/work
tinycss2 @ file:///work/ci_py311/tinycss2_1676823757641/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tornado @ file:///croot/tornado_1690848263220/work
traitlets @ file:///work/ci_py311/traitlets_1676823305040/work
typing_extensions @ file:///croot/typing_extensions_1690297465030/work
tzdata==2023.3
urllib3 @ file:///croot/urllib3_1686163155763/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client @ file:///work/ci_py311/websocket-client_1676824890004/work
widgetsnbextension @ file:///croot/widgetsnbextension_1679313860248/work
y-py @ file:///croot/y-py_1683555143488/work
ypy-websocket @ file:///croot/ypy-websocket_1684171737040/work
zipp==3.15.0
```

**Comment by raph-luc** [comment] 2023-09-22 20:11
Can't reproduce, works fine here with all Fluent versions and local VSCode running Jupyter notebook. 

This sounds like a user setup issue, not a bug.

How are you running the Jupyter notebook, is that in VSCode as well?

**Comment by g-pagliuca** [comment] 2023-09-24 12:41
Hi, thanks for the quick feedback.
Nothing special, I was playing with pyfluent within jupyter lab, more details on the screenshot.

As mentioned the fluent GUI works just fine but the python process is hanging

![screenshot](https://github.com/ansys/pyfluent/assets/67365525/6efed607-3ccf-43d8-a1f6-30b5f6b96512)

**Comment by g-pagliuca** [comment] 2023-09-24 13:13
Not sure this helps but when I kill the execution I get this tracelog:

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[2], line 1
----> 1 solver_session = pyfluent.launch_fluent(mode='solver', show_gui=True)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/launcher/launcher.py:614, in launch_fluent(product_version, version, precision, processor_count, journal_filepath, start_timeout, additional_arguments, env, start_instance, ip, port, cleanup_on_exit, start_transcript, show_gui, case_filepath, case_data_filepath, lightweight_mode, mode, server_info_filepath, password, py, gpu, cwd, topy, **kwargs)
    610 subprocess.Popen(launch_string, **kwargs)
    612 _await_fluent_launch(server_info_filepath, start_timeout, sifile_last_mtime)
--> 614 session = new_session.create_from_server_info_file(
    615     server_info_filepath=server_info_filepath,
    616     cleanup_on_exit=cleanup_on_exit,
    617     start_transcript=start_transcript,
    618     launcher_args=argvals,
    619 )
    620 if case_filepath:
    621     if meshing_mode:

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/session.py:120, in BaseSession.create_from_server_info_file(cls, server_info_filepath, cleanup_on_exit, start_transcript, launcher_args)
     97 """Create a Session instance from server-info file.
     98 
     99 Parameters
   (...)
    116     Session instance
    117 """
    118 ip, port, password = _parse_server_info_file(server_info_filepath)
    119 session = cls(
--> 120     fluent_connection=FluentConnection(
    121         ip=ip,
    122         port=port,
    123         password=password,
    124         cleanup_on_exit=cleanup_on_exit,
    125         start_transcript=start_transcript,
    126         launcher_args=launcher_args,
    127     )
    128 )
    129 return session

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/fluent_connection.py:186, in FluentConnection.__init__(self, start_timeout, ip, port, password, channel, cleanup_on_exit, start_transcript, remote_instance, launcher_args)
    183 self.health_check_service = HealthCheckService(self._channel, self._metadata)
    185 counter = 0
--> 186 while not self.health_check_service.is_serving:
    187     time.sleep(1)
    188     counter += 1

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/health_check.py:91, in HealthCheckService.is_serving(self)
     88 @property
     89 def is_serving(self) -> bool:
     90     """Checks whether Fluent is serving."""
---> 91     return True if self.status() == "SERVING" else False

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/health_check.py:82, in HealthCheckService.status(self)
     80 if self._channel:
     81     try:
---> 82         return self.check_health()
     83     except Exception:
     84         return self.Status.NOT_SERVING.name

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/error_handler.py:13, in catch_grpc_error.<locals>.func(*args, **kwargs)
     10 @functools.wraps(f)
     11 def func(*args, **kwargs) -> Callable:
     12     try:
---> 13         return f(*args, **kwargs)
     14     except grpc.RpcError as ex:
     15         raise RuntimeError(ex.details()) from None

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/health_check.py:50, in HealthCheckService.check_health(self)
     42 """Check the health of the Fluent connection.
     43 
     44 Returns
   (...)
     47     "SERVING" or "NOT_SERVING"
     48 """
     49 request = HealthCheckModule.HealthCheckRequest()
---> 50 response = self._stub.Check(request, metadata=self._metadata)
     51 return HealthCheckService.Status(response.status).name

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:247, in _UnaryUnaryMultiCallable.__call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    240 def __call__(self,
    241              request: Any,
    242              timeout: Optional[float] = None,
   (...)
    245              wait_for_ready: Optional[bool] = None,
    246              compression: Optional[grpc.Compression] = None) -> Any:
--> 247     response, ignored_call = self._with_call(request,
    248                                              timeout=timeout,
    249                                              metadata=metadata,
    250                                              credentials=credentials,
    251                                              wait_for_ready=wait_for_ready,
    252                                              compression=compression)
    253     return response

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:287, in _UnaryUnaryMultiCallable._with_call(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    284     except Exception as exception:  # pylint:disable=broad-except
    285         return _FailureOutcome(exception, sys.exc_info()[2])
--> 287 call = self._interceptor.intercept_unary_unary(continuation,
    288                                                client_call_details,
    289                                                request)
    290 return call.result(), call

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py:47, in TracingInterceptor.intercept_unary_unary(self, continuation, client_call_details, request)
     40 def intercept_unary_unary(
     41     self,
     42     continuation: Any,
     43     client_call_details: grpc.ClientCallDetails,
     44     request: Any,
     45 ) -> Any:
     46     """Intercept unary-unary call for tracing."""
---> 47     return self._intercept_call(continuation, client_call_details, request)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py:32, in TracingInterceptor._intercept_call(self, continuation, client_call_details, request)
     21 def _intercept_call(
     22     self,
     23     continuation: Any,
     24     client_call_details: grpc.ClientCallDetails,
     25     request: Any,
     26 ):
     27     network_logger.debug(
     28         "GRPC_TRACE: rpc = %s, request = %s",
     29         client_call_details.method,
     30         MessageToDict(request),
     31     )
---> 32     response = continuation(client_call_details, request)
     33     if not response.exception():
     34         network_logger.debug(
     35             "GRPC_TRACE: response = %s",
     36             MessageToDict(response.result()),
     37         )

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:274, in _UnaryUnaryMultiCallable._with_call.<locals>.continuation(new_details, request)
    269 (new_method, new_timeout, new_metadata, new_credentials,
    270  new_wait_for_ready,
    271  new_compression) = (_unwrap_client_call_details(
    272      new_details, client_call_details))
    273 try:
--> 274     response, call = self._thunk(new_method).with_call(
    275         request,
    276         timeout=new_timeout,
    277         metadata=new_metadata,
    278         credentials=new_credentials,
    279         wait_for_ready=new_wait_for_ready,
    280         compression=new_compression)
    281     return _UnaryOutcome(response, call)
    282 except grpc.RpcError as rpc_error:

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:301, in _UnaryUnaryMultiCallable.with_call(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    292 def with_call(
    293     self,
    294     request: Any,
   (...)
    299     compression: Optional[grpc.Compression] = None
    300 ) -> Tuple[Any, grpc.Call]:
--> 301     return self._with_call(request,
    302                            timeout=timeout,
    303                            metadata=metadata,
    304                            credentials=credentials,
    305                            wait_for_ready=wait_for_ready,
    306                            compression=compression)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:287, in _UnaryUnaryMultiCallable._with_call(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    284     except Exception as exception:  # pylint:disable=broad-except
    285         return _FailureOutcome(exception, sys.exc_info()[2])
--> 287 call = self._interceptor.intercept_unary_unary(continuation,
    288                                                client_call_details,
    289                                                request)
    290 return call.result(), call

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py:125, in BatchInterceptor.intercept_unary_unary(self, continuation, client_call_details, request)
    118 def intercept_unary_unary(
    119     self,
    120     continuation: Any,
    121     client_call_details: grpc.ClientCallDetails,
    122     request: Any,
    123 ) -> Any:
    124     """Intercept unary-unary call for batch operation."""
--> 125     return self._intercept_call(continuation, client_call_details, request)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py:116, in BatchInterceptor._intercept_call(self, continuation, client_call_details, request)
    113     if op.queued:
    114         return BatchedFuture(op.response_cls)
--> 116 return continuation(client_call_details, request)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_interceptor.py:274, in _UnaryUnaryMultiCallable._with_call.<locals>.continuation(new_details, request)
    269 (new_method, new_timeout, new_metadata, new_credentials,
    270  new_wait_for_ready,
    271  new_compression) = (_unwrap_client_call_details(
    272      new_details, client_call_details))
    273 try:
--> 274     response, call = self._thunk(new_method).with_call(
    275         request,
    276         timeout=new_timeout,
    277         metadata=new_metadata,
    278         credentials=new_credentials,
    279         wait_for_ready=new_wait_for_ready,
    280         compression=new_compression)
    281     return _UnaryOutcome(response, call)
    282 except grpc.RpcError as rpc_error:

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_channel.py:1041, in _UnaryUnaryMultiCallable.with_call(self, request, timeout, metadata, credentials, wait_for_ready, compression)
   1032 def with_call(
   1033     self,
   1034     request: Any,
   (...)
   1039     compression: Optional[grpc.Compression] = None
   1040 ) -> Tuple[Any, grpc.Call]:
-> 1041     state, call, = self._blocking(request, timeout, metadata, credentials,
   1042                                   wait_for_ready, compression)
   1043     return _end_unary_response_blocking(state, call, True, None)

File /glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/pyfluent/lib/python3.11/site-packages/grpc/_channel.py:1017, in _UnaryUnaryMultiCallable._blocking(self, request, timeout, metadata, credentials, wait_for_ready, compression)
   1009 else:
   1010     call = self._channel.segregated_call(
   1011         cygrpc.PropagationConstants.GRPC_PROPAGATE_DEFAULTS,
   1012         self._method, None, _determine_deadline(deadline), metadata,
   (...)
   1015             None,
   1016         ),), self._context)
-> 1017     event = call.next_event()
   1018     _handle_event(event, state, self._response_deserializer)
   1019     return state, call

File src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi:338, in grpc._cython.cygrpc.SegregatedCall.next_event()

File src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi:169, in grpc._cython.cygrpc._next_call_event()

File src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi:163, in grpc._cython.cygrpc._next_call_event()

File src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi:78, in grpc._cython.cygrpc._latent_event()

File src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi:61, in grpc._cython.cygrpc._internal_latent_event()

File src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi:42, in grpc._cython.cygrpc._next()

KeyboardInterrupt: 
```

**Comment by raph-luc** [comment] 2023-09-25 15:27
Thanks for reporting this issue, but I tried Jupyter Lab PyFluent with Fluent v241, v232, v231 and v222 and they all work fine on my end, so I can't reproduce this issue (or it has already been fixed by other changes in recent versions).

Can you try using a newer version of PyFluent? According to the list of installed packages you provided, you are using an old version of PyFluent (0.15.0). Try PyFluent 0.17.1 using `pip install ansys-fluent-core==0.17.1`.

**Comment by g-pagliuca** [comment] 2023-09-26 10:24
Yeah, I tried this, my current env is:

```
ansys-api-fluent                      0.3.17
ansys-api-platform-instancemanagement 1.0.0
ansys-fluent-core                     0.17.1
```

Let me try to create a new env from scratch

**Comment by mkundu1** [comment] 2023-09-26 13:01
Can you enable the logging and share the generated pyfluent.log in the working directory?
```
import ansys.fluent.core as pyfluent
pyfluent.logging.enable()
...
```
Somehow the initial connection is not established, although we should get a timeout.

**Comment by g-pagliuca** [comment] 2023-09-26 13:09
OK, this is funny. In the past I used pyfluent so I tried downgrading ansys-fluent-core and with these settings it sort of works:

```
ansys-api-platform-instancemanagement 1.0.0
ansys-fluent-core                     0.11.0
ansys-platform-instancemanagement     1.1.2
```
I get back the control but there is no real established connection since `session.check_health()` returns not serving

After upgrading to the latest version I got rthis in the log file:

```
2023-09-26 15:07:05,273 pyfluent.networking   DEBUG    Cannot use 127.0.0.1 as remoting ip
2023-09-26 15:07:05,303 pyfluent.networking   DEBUG    Cannot use 127.0.0.1 as remoting ip
2023-09-26 15:07:05,303 pyfluent.launcher     DEBUG    Launching Fluent with command: /glb/apps/hpc/EasyBuild/software/rhel/7/ANSYS/2023R1/v231/fluent/bin/fluent 3ddp   -sifile="/tmp/serverinfo-zorcjo2p.txt" -nm
2023-09-26 15:07:06,307 pyfluent.launcher     INFO     Waiting for Fluent to launch...29 seconds remaining
2023-09-26 15:07:07,308 pyfluent.launcher     INFO     Waiting for Fluent to launch...28 seconds remaining
2023-09-26 15:07:08,310 pyfluent.launcher     INFO     Waiting for Fluent to launch...27 seconds remaining
2023-09-26 15:07:09,314 pyfluent.launcher     INFO     Waiting for Fluent to launch...26 seconds remaining
2023-09-26 15:07:10,317 pyfluent.launcher     INFO     Waiting for Fluent to launch...25 seconds remaining
2023-09-26 15:07:11,318 pyfluent.launcher     INFO     Fluent has been successfully launched.
2023-09-26 15:07:11,320 pyfluent.networking   DEBUG    GRPC_TRACE: rpc = /grpc.health.v1.Health/Check, request = {} 
```

**Comment by mkundu1** [comment] 2023-09-26 14:07
From these 2 messages it seems to be some issue in the network configuration.
```
Cannot use 127.0.0.1 as remoting ip
Cannot use 127.0.0.1 as remoting ip
```
In the server GUI, can you execute the TUI `server/print-server-address` to see what is written in the server-info file? I think the IP address written out by Fluent is not reachable from the client.

Also, you can check whether Fluent's visualization client can be launched or not - from Fluent GUI File -> Application -> Visualization Client.

**Comment by g-pagliuca** [comment] 2023-09-27 03:06
All right, here the output:

```
********************************************************************
************************ Server Info********************************
********************************************************************
 Host Address : 145.59.71.128 
 Port Number  : 6488 
********************************************************************
********************************************************************
```

> Also, you can check whether Fluent's visualization client can be launched or not - from Fluent GUI, File -> Application -> Visualization Client.

Yes, I can start it

![image](https://github.com/ansys/pyfluent/assets/67365525/b158e2ef-068e-4d04-8c9a-dac3254b2462)

**Comment by raph-luc** [comment] 2023-09-27 13:44
@g-pagliuca You can start the Visualization Client, but does it actually work? After starting it as Mainak suggested, you should automatically get a screen like (for both 2023 R1 and 2022 R2):
![image](https://github.com/ansys/pyfluent/assets/132297401/bd4956a7-9c5c-4c27-8c0b-ce443a920851)

**Comment by raph-luc** [comment] 2023-09-27 17:13
So the issue is not related to PyFluent then, as the Fluent session you are running is being blocked or prevented from communicating with any other applications in your local machine. 

Can you try temporarily disabling the firewall in your machine and then testing again?

**Comment by seanpearsonuk** [comment] 2023-10-03 08:36
@mkundu1 @raph-luc assigning you while the user is being supported

**Comment by raph-luc** [comment] 2023-10-26 13:15
Closing due to inactivity, feel free to reopen and comment if issue isn't resolved, or someone else has the same issue

**Closed by raph-luc** 2023-10-26 13:15 UTC
Labels: user issue

**Comment by g-pagliuca** [comment] 2024-02-12 10:24
Dear all, sorry for the necro-posting but I still have this issue and the interaction with the support team led nowhere (there have been very kind!). I understand this is not a pyfluent issue per se but maybe you have new ideas/suggestions for me.

Following an idea from the support team I tried was a workaround to bypass the server-client connection:

```
session = pyfluent.launch_fluent(
     version='3d',
     additional_arguments="-node -mport 145.59.71.230:145.59.71.230:3016:0",
     cleanup_on_exit=True,
 )
```

But this was ineffective.

Any suggestions?

**Comment by mkundu1** [comment] 2024-02-12 12:57
Looking at the Fluent - Remote Visualization Client connection error, I think the ip address written out by Fluent in the server_info file is incorrect. While launching the Remote Visualization Client Fluent writes out a server_info file in the working directory (default location) which is read back by the client. Can you compare the ip address with the `ifconfig` output of your machine? You can force Fluent to write a different ip address (if `ifconfig` output shows a different value) by setting the environment variable `REMOTING_SERVER_ADDRESS` before launching Fluent. Please check [Remote Visualization Client Environment Variables section](https://ansyshelp.ansys.com/account/secured?returnurl=/Views/Secured/corp/v241/en/flu_ug_workspaces/flu_ug_remote_client_environment_variables.html) in Fluent's User Guide for details about this environment variable. If the server and client are both running on the same machine, setting `REMOTING_SERVER_ADDRESS` to `localhost` or `127.0.0.1` usually works. This environment variable can be used during PyFluent - Fluent conenction and can be set before staring PyFluent.

**Comment by g-pagliuca** [comment] 2024-02-12 13:38
Thanks for the reply. Unfortunately it did not work, more details below

**Starting a new session**
Setting this: 
`os.environ["REMOTING_SERVER_ADDRESS"] = "localhost"`

and trying to start a new session with `session = pyfluent.launch_fluent()` I get from the debugger this:

```
/glb/apps/hpc/EasyBuild/software/rhel/7/ANSYS/2023R2/v232/fluent/fluent23.2.0/bin/fluent -r23.2.0 3ddp -sifile=/tmp/serverinfo-8kjxxznm.txt -nm -hidden
/glb/apps/hpc/EasyBuild/software/rhel/7/ANSYS/2023R2/v232/fluent/fluent23.2.0/cortex/lnamd64/cortex.23.2.0 -f fluent -sifile=/tmp/serverinfo-8kjxxznm.txt -nm -hidden (fluent "3ddp -pshmem  -host -r23.2.0 -t1 -mpi=intel -path/glb/apps/hpc/EasyBuild/software/rhel/7/ANSYS/2023R2/v232/fluent -ssh")
```

The txt file mentioned above is empty and eventually I get the error message:
`pyfluent.launcher ERROR: Exception caught - RuntimeError: failed to connect to all addresses; last error: UNKNOWN: ipv4:185.46.212.90:80: HTTP proxy returned response code 403`


**Connecting to an existing session**
If I start a fluent instance (with `export REMOTING_SERVER_ADDRESS="localhost"`) and then I start a server I get this serverinfo file:

```
localhost:27755
3mhrjgnx
```

Trying to connect to it with `session = pyfluent.connect_to_fluent(ip="localhost", port=27755)` results in a very similar error message:
`
RuntimeError: failed to connect to all addresses; last error: UNKNOWN: ipv4:185.46.212.90:80: HTTP proxy returned response code 40`
